### ISSUE TITLE
scaling of ELK

### ISSUE THREAD

**Issue by vorozhko** [githubcdr/docker-elk#1]
Hello
How do your scale this setup?
For example number of elasticsearch nodes across several servers.

Best
Yaroslav

**Comment by githubcdr** [comment]
Hello,

My best bet is to detach elasticsearch from this setup and use the logstash config to specify the HA endpoint. Or you could try yo use a plugin to auto discover elasticsearch peers.

Would be nice to study this but I have had no need for such a setup.
