### ISSUE TITLE
Unable to connect to Elasticsearch at http://localhost:9200. 

### ISSUE THREAD

**Issue by pcouas** [githubcdr/docker-elk#5]
Hi 

I have started your docker and i could connect to kibana on 5601 port but, i have following error message
"Unable to connect to Elasticsearch at http://localhost:9200. "
I use dockertoolbox on windows10

Regards
Phil

**Comment by githubcdr** [comment]
Hi,


It might be related to Elasticsearch not being able to write to /var/lib/elasticsearch. Can you try to start the container with a clean directory to see if it starts? Note that it takes some time to bring ES online.

Also please inspect logs via docker logs and paste errors.
